name: material
description: Set of material design icons packed in a single ttf font file. Works on all platforms.
version: 1.0.0+2
homepage: https://github.com/xclud
repository: https://github.com/xclud/flutter_material

environment:
 sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
 fonts:
   - family: Material
     fonts:
       - asset: lib/fonts/material.ttf
